title: <p align="center"> Mani Sankar Reddy Kalluri </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/maniheist">GitHub</a>
  
  <br>   
  I'm working on backend applications, building scalable systems with a focus on performance, security, and data handling.
I work extensively with technologies like Big Data, Apache Spark, and distributed systems, solving real-time processing problems.
  <br>
  </p>
